### ISSUE TITLE
Raw dimensions differ between Windows and Ubuntu

### ISSUE THREAD

**Issue by willgearty** [ropensci/rsvg#37]
I've found that the dimensions of the output of `rsvg_raw()` appear to be somewhat OS-dependent.

Here's a reproducible example with R 4.2.2:
```r
# on windows
test <- rsvg_raw("https://images.phylopic.org/images/35787884-905e-4d24-9111-f9b93fe47834/vector.svg")
dim(test)
[1]      4    1729     944
```

```r
# on ubuntu 22.04
test <- rsvg_raw("https://images.phylopic.org/images/35787884-905e-4d24-9111-f9b93fe47834/vector.svg")
dim(test)
[1]      4    1728     943
```

When I look at the original svg file, the width is 1728.7859 and the height is 943.78149, so perhaps this is a rounding issue?

**Comment by jeroen** [comment]
It's probably caused by a different version of librsvg.

**Comment by willgearty** [comment]
Ah, you are right, the windows package comes with librsvg 2.48.8, whereas I installed librsvg2-dev 2.52.5 in my Ubuntu environment. I don't see any other versions available for download for ubuntu via apt, unless I'm looking in the wrong place? Or maybe there's a way to update the version on my Windows machine?

**Comment by willgearty** [comment]
I was able to switch to using Ubuntu 20.04 in Github Actions and resolve this. It looks like the most recent version of librsvg on Ubuntu 20.04 is only 2.48.9, which seems close enough to 2.48.8 to not cause the issue anymore.
