### ISSUE TITLE
Feature request: Add rsvg_tiff() for SVG to TIFF conversion

### ISSUE THREAD

**Issue by selkamand** [ropensci/rsvg#45]
Hi,

Thanks so much for your work on this package!

I was wondering whether you might consider adding an SVG to TIFF conversion function; e.g. `rsvg_tiff()` similar to `rsvg::rsvg_png()`?

The format commonly required for figures submitted to scientific journals, so having a ready-made conversion function would certainly come in handy!

**Comment by jeroen** [comment]
It might be easier to accomplish this with the magick package, for example:

```r
library(magick)
tiger <- image_read_svg("http://jeroen.github.io/images/tiger.svg")
image_write(tiger, 'tiger.tiff')
```

**Comment by selkamand** [comment]
Thanks @jeroen! 

Workaround works great. I will assume this being easy without rsvg means there is little appetite to add a dedicated `rsvg_tiff()` function that conforms with the rsvg API - and therefore close this issue.

Thanks again for your work on this package!
